[env:control_pad_32u4]
platform = atmelavr
board = leonardo
framework = arduino
monitor_speed = 115200
lib_deps =
  MHeironimus/Joystick@^2.1.1

[env:native]
platform = native
test_framework = unity
build_src_filter = +<debounce.cpp>
